### ISSUE TITLE
PHP 8.1 - Passing null to parameter #2 ($subject) of type string is deprecated in .../vendor/consolidation/site-alias/src/SiteSpecParser.php on line 144

### ISSUE THREAD

**Issue by mrweiner** [consolidation/site-alias#48]
I think this is a separate error from the one addressed in https://github.com/consolidation/site-alias/pull/46.

**Comment by mrweiner** [comment]
Created a PR: https://github.com/consolidation/site-alias/pull/49

**Comment by HnLn** [comment]
[preg_match_null_notification.patch.txt](https://github.com/consolidation/site-alias/files/7969464/preg_match_null_notification.patch.txt)

``` 
   protected function match($spec)
    {
        if ($spec === null) {
            return [];
        }

```
