### ISSUE TITLE
[suggestion] Disable repository "Releases" feature

### ISSUE THREAD

**Issue by esolitos** [consolidation/site-alias#62]
This is only a suggestion to improve the developer experience, feel free to close if you don't agree, no strings attached. 😄 

Right now when one opens the GitHub repo page the sidebar suggests that the latest version is the **3.0.0**, however there are quite a few releases after this, but because the "release" feature has not been used since they are only visible when clicking on "Tags".

![image](https://user-images.githubusercontent.com/401819/234824926-8295efb9-cd1a-4bad-8762-cce068518f3d.png)

This of course does not prevent any functionality to work, but is just confusing for a moment when landing on this page.

My suggestion is to take one of the following routes:
- Disable the "Releases" functionality on the repository settings
- Resume using the "Releases" functionality 

Either way, thanks for your project!

**Comment by esolitos** [comment]
Thanks for quick the answer and the background information.

> I don't think there's any way to disable the releases functionality 

🤦🏼  Indeed, somehow I was sure that it was a checkbox in the **Features** section of the repo settings. 😅  

An alternative solution would be to automatically create a release when a tag is pushed using GH Actions. I can open a PR if this is an acceptable solution for you. :)

**Comment by greg-1-anderson** [comment]
Yes, that would be appreciated.
